#!/usr/bin/python3
from sys import argv

with open(argv[1])as f:
    for line in f:
        num = int(line)
        print("{:d}=".format(num), end='')
        if num % 2 == 0:
            print("{}*2".format(num // 2))
            continue
        for n in range(3, num, 2):
            if num % n == 0:
                factor = num // n
                for m in range(3, factor, 2):
                    if factor % m == 0 or m == 0:
                        break
                print("{} * {}".format, n))
                break
